### ISSUE TITLE
/templates returns empty object

### ISSUE THREAD

**Issue by FlashDog123** [sendgrid/docs#4724] opened 2018-11-06 14:25 UTC
Hi guys,

I'm trying to get all my transactional templates through the /v3/templates endpoint, but it returns a empty object(while i currently have 2 templates defined). After some trail and error, I noticed that the endpoint does return some templates after I created a template through the API, not the interface. But these templates are legacy templates, without handlebar.js support. 

It looks to me like a bug, but if this is correct then the doc has incorrect text.

Thanks!

**Comment by vaishnavhiren1993** [comment] 2018-11-26 18:05
Can you share your code and description of error to help you batter

**Comment by tjfdud** [comment] 2019-01-16 19:04
I've reproduced this issue as well.

I created couple of transactional templates using design editor or code editor from the Web UI. 
After then I tried to work with the templates using the APIs. Getting a template using the template id works but it fails to retrieve all transactional templates. 

- OK GET https://api.sendgrid.com/v3/templates/d-fxxxxx
- NO GET https://api.sendgrid.com/v3/templates
![image](https://user-images.githubusercontent.com/26883383/51272028-0075ff80-1997-11e9-92f0-e04fe0495134.png)
Also tried with https://api.sendgrid.com/v3/templates?generations=legacy but this returns empty list as well.

**Comment by ksigler7** [comment] 2019-01-16 22:03
hey all, we're working on getting the docs all merged in, but for now, here are the docs for that GET - https://dynamic-templates.api-docs.io/3.0/templates/retrieve-a-specific-transactional-template-version

**Closed by ksigler7** 2019-01-16 22:03 UTC

**Comment by scottwilson312** [comment] 2019-12-01 04:59
I believe this is still an issue!.I needed to specify `generations=dynamic` in order to see any of my templates.

The docs simply state the endpoint "Retrieves all Templates", and make no reference to the `generations` query parameter.

**Comment by escobarjj** [comment] 2020-05-26 00:58
Hi! Same problem here... The _templates.get() is it not supposed to retrieve all existing templates as specified in docs and also script examples?

**Comment by villemuittari** [comment] 2020-11-23 07:10
Seems like this is not fixed yet to the documentation even the issue is closed

**Comment by Whatthefoxsays** [comment] 2020-11-25 16:08
@villemuittari, please use this API reference in the future:  https://sendgrid.api-docs.io/v3.0/transactional-templates/create-a-transactional-template

Any docs pages with API_Reference are out of date and we're working really hard with ops and IT to get it taken down and redirected. Thanks for your patience!
