### ISSUE TITLE
Azure SendGrid signup broken

### ISSUE THREAD

**Issue by IanElsinga** [sendgrid/docs#5474] opened 2019-08-09 21:39 UTC
## Expected content

Hi, I have tried everywhere to get support for this.  I am trying to sign up for SendGrid on Azure but it won't load the legal terms and therefore won't allow me to sign up.  I have tried Azure support, SendGrid support, no-one will even allow me to open a ticket.  

The error SendGrid Create a new SendGrid Account in azure is initially:  

>We were unable to get information for your resources.

Then it says:

>Part's onInputsSet promise failed.(id: Microsoft_Azure_Marketplace-fx-010-00b) Error: message: LegalTermsGrid.onLegalTermsAccepted() must not be called before the legal terms have finished loading. stack: Error: LegalTermsGrid.onLegalTermsAccepted() must not be called before the legal terms have finished loading. at n.onLegalTermsAccepted (https://afd.hosting.portal.azure.net/marketplace/Content/Dynamic/8GSLuiIynVbf.js:4:30103) at Object.mapOutgoingDataForCollector (https://afd.hosting.portal.azure.net/marketplace/Content/Dynamic/8GSLuiIynVbf.js:6:2803) at f._discardEditScopeAndSendResult (https://portal.azure.com/Content/Dynamic/adaluICNCNBe.js:300:2689) at i (https://portal.azure.com/Content/Dynamic/adaluICNCNBe.js:300:2257) at https://portal.azure.com/Content/Dynamic/adaluICNCNBe.js:300:2352 at https://portal.azure.com/Content/Dynamic/adaluICNCNBe.js:70:565 at Array.map () at Object.triggerCallbacks (https://portal.azure.com/Content/Dynamic/adaluICNCNBe.js:70:537) at r.n.updatePartInputValues (https://portal.azure.com/Content/Dynamic/adaluICNCNBe.js:68:1674) at r.updatePartInputValues (https://portal.azure.com/Content/Dynamic/adaluICNCNBe.js:72:2088)
Reload tile
Summary
Session ID
60819f992d3f49e888fdfe5be85b5cc9
Resource ID
Not available
Extension
Microsoft_Azure_Marketplace
Content
LegalTermsV2Part
Error code
500

**Link to page**:
https://portal.azure.com/#

**Comment by clineer** [comment] 2019-08-13 05:04
Hey I noticed your post and I am getting a similar error for an Azure subscription. There is something wrong with the Azure portal controls - definitely a Microsoft bug. I am seeing something like this for the integration account and logic app controls. I have not seen many people with this kind of error. I know some Microsoft people and will be contacting them directly and will definitely mention your issue too.

**Comment by clineer** [comment] 2019-08-13 19:12
Hey Ian, we identified the issue is related to permissions. Try getting your admin to grant you owner rights for SendGrid and see if your error goes away.

**Comment by Whatthefoxsays** [comment] 2019-08-13 22:04
Thanks @clineer for addressing this! Once I get confirmation that @IanElsinga is successful I will close this issue.

**Comment by clineer** [comment] 2019-08-15 15:43
Thanks @Whatthefoxsays

**Comment by IanElsinga** [comment] 2019-08-15 20:14
Hi @clineer thanks very much for addressing this, but it still doesn't work.  Same message when creating a sendgrid account:  "We were unable to get information for your resources" and then the same error message as above.  

I am not sure what you mean by granting owner rights for SendGrid - I am the admin, and I am trying to add a SendGrid resource so I can't even create the resource. 

Very much appreciate anything you can do - it's frustrating that I can't report azure bugs as our subscription as a Microsoft Partner does not allow that.

**Comment by clineer** [comment] 2019-08-15 20:27
I found if you private message @AzureAupport on Twitter they give you some support there. I did mention your issue to them already. I can reply back to them too. Do you have a Twitter handle?

**Comment by IanElsinga** [comment] 2019-08-15 20:34
Oh ok, you can use @ianelsinga  
Thanks!

**Comment by Agazoth** [comment] 2019-08-16 05:48
I get the exact same error as Global Admin:
![createsendgrid](https://user-images.githubusercontent.com/15127301/63145884-6e4fdb80-bff9-11e9-9418-48dc7c47de1b.PNG)

When clicking OK, I get:
![sendgriderror](https://user-images.githubusercontent.com/15127301/63146150-3eed9e80-bffa-11e9-9505-ba53a3ca6829.PNG)

**Comment by Agazoth** [comment] 2019-08-16 08:44
And now it suddenly worked ...

**Comment by IanElsinga** [comment] 2019-08-16 12:24
I just tried a couple of times, refreshing the page, exact same error as @Agazoth pasted above...

**Comment by clineer** [comment] 2019-08-17 17:10
I have a similar error happening again and it continues failing in IE Edge and not in Chrome so the browser has something to do with it but I am just not sure why.

**Comment by IanElsinga** [comment] 2019-08-18 12:33
All my attempts were in Chrome...

**Comment by buboi** [comment] 2019-11-03 05:30
Did this issue get resolved? I got same problem now.

**Comment by IanElsinga** [comment] 2019-11-03 13:43
Never resolved.  I had to give up on it.   It's been about 3 months and the bug is still there.  I'm very wary of putting anything mission-critical on Azure as a result of this experience!

**Comment by buboi** [comment] 2019-11-03 16:13
![image](https://user-images.githubusercontent.com/1837875/68088183-77817380-fe97-11e9-852e-9715bf6c1d21.png)
I found there is an error, "BadRequest". 
It seems Azure API returned this.

I tried another mail service, MailJet got the same result.

**Comment by joseabadg** [comment] 2020-01-17 14:35
Any solutions about it? i have the same problem creating DynamicsApp in Azure

**Comment by lloydjatkinson** [comment] 2020-01-18 01:01
I have a similar problem. I created the resource in Azure, but it seems I can't then login to SendGrids website, making the feature more or less useless. I can't login to setup templates for example. I don't even know how to get the API key from the Azure resource.

**Comment by joseabadg** [comment] 2020-01-28 09:30
![image](https://user-images.githubusercontent.com/2313042/73251351-15e05500-41b9-11ea-9ac9-41add34e09ea.png) Same problem, again..

**Comment by pb-dashly** [comment] 2020-01-28 16:56
Same problem. Created a SendGrid account using the Azure integrated signup ("Manage")  - thought it was great - but now when I try to log back in, "Manage" asks for a username & password (which I don't know). I checked the signup credentials Azure used in the SendGrid Activty Log, but the credentials shown in there (well the ones I've tried) don't let me login to SendGrid.

**Comment by clineer** [comment] 2020-01-28 18:02
Hey there is an Azure support twitter account that gets super fast support replies. I mentioned this issue there a few months back. Please reach out to them and they can help you.

Thanks,
Ben

**Comment by dcadlereii** [comment] 2020-03-20 13:54
I am having a similar issue. I am not getting any errors during setup. However, once setup in Azure is complete and I click on the Manage link, I cannot log in with the username and password I provided during setup. I have also not received a validation email from SendGrid, which is why I think I can't log in yet. SendGrid site says you cannot log in until you have validated your email.

**Comment by buboi** [comment] 2020-04-10 12:57
I got the MS response, SendGrid service is not available in China.

**Comment by compnetsys** [comment] 2020-07-29 17:38
Well its July 29th and I have this exact issue. Created an account, unable to access it through the send-grid website. Unable to delete it from azure, unable to create a new one.. I am hosed

**Comment by meglio** [comment] 2020-10-27 07:24
I tried changing first/last name and other contact details 10+ times throughout a few days, and it finally went through. So might be some validation issue from the SendGrid side.

**Comment by LordGordonQ** [comment] 2020-10-30 14:26
I had a similar issue and my user was already owner of the subscription and resource group where SendGrid was created. After adding the owner role explicitly to the SendGrid service, everything works.

It seems that role inheritance is broken.

**Closed** 2021-05-25 19:24 UTC

**Comment by lloydjatkinson** [comment] 2021-05-25 19:32
Was this even investigated before it was closed?

**Comment by clineer** [comment] 2021-05-25 19:56
Yeah I agree it seemed like it wasn't solved

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
