### ISSUE TITLE
Footer doesn't stick to bottom of page

### ISSUE THREAD

**Issue by eddiezane** [sendgrid/docs#508] opened 2014-08-11 18:57 UTC
![screen shot 2014-08-11 at 2 54 47 pm](https://cloud.githubusercontent.com/assets/959573/3880934/42a83b3a-2189-11e4-8dfa-d090f3a2e264.png)

**Comment by trotha01** [comment] 2015-02-13 16:11
@eddiezane @mbernier This seems to be fixed as far as I can tell? Can we close this issue?

Are there reproducible steps for this Eddie?

**Comment by eddiezane** [comment] 2015-02-13 17:29
@trotha01 if it looks good on a thunderbolt display then it's GTG

**Comment by trotha01** [comment] 2015-02-13 20:48
Ah, I see

**Comment by mbernier** [comment] 2015-02-17 17:23
I am working with @two24studios to clean up some of the design for docs, this is one of the things we'll fix up.

**Comment by trotha01** [comment] 2015-02-18 14:33
nice!

**Comment by mbernier** [comment] 2016-07-27 15:18
This has been fixed

**Closed by mbernier** 2016-07-27 15:18 UTC
