### ISSUE TITLE
BadRequest with Base64 image attachment

### ISSUE THREAD

**Issue by ChristopheHvd** [sendgrid/docs#2527] opened 2017-03-03 15:12 UTC
I try to add a Base64 encoded image from my web app.
When I add it directly to the message as an attachement, I got a BadRequest.
ex : 
`            var msg = MailHelper.CreateSingleEmail(from, to, subject, body, body);
var base64ImgAttachment = "data:image/png;iVBORw0......"; // the base64 encoded image
                msg.AddAttachment("Capture", base64ImgAttachment, "image/png");
`

So I tried to remove the metadata from the base64 string and keep only the image itself : 

 `            var msg = MailHelper.CreateSingleEmail(from, to, subject, body, body);
var base64ImgAttachment = "iVBORw0......"; // the base64 encoded image
                msg.AddAttachment("Capture", base64ImgAttachment, "image/png");
`

and it works. 
But the received attached file comes with no extension. So I cannot open it normally...

Any idea?

**Comment by thinkingserious** [comment] 2017-03-03 16:15
Hello @ChristopheHvd,

What function are you using to create the base64 string?

How about: `Convert.ToBase64String(content);`

Thanks!

**Comment by ChristopheHvd** [comment] 2017-03-05 17:35
I receive the base64 from my web app directly, with the metadata at the beginning
`data:image/png;base64,iVBORw0K....`

Should I blame the web app though?

**Comment by thinkingserious** [comment] 2017-03-07 07:55
Hi @ChristopheHvd,

It should work with the metadata removed. Can you send the attachment to dx@sendgrid.com, so that I can try to reproduce the error?

With Best Regards,

Elmer

**Comment by ChristopheHvd** [comment] 2017-03-07 08:12
@thinkingserious , I'll send you a text file with the data.
Thank you for your support.
Regards,
Chris

**Comment by thinkingserious** [comment] 2017-03-07 23:09
Hello @ChristopheHvd,

Here was what worked for me:

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Threading.Tasks;

namespace Example
{
	internal class Example
	{
		private static void Main()
		{
			Execute().Wait();
		}

		static async Task Execute()
		{
			var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
			var client = new SendGridClient(apiKey);
			var msg = new SendGridMessage()
			{
				From = new EmailAddress("dx@sendgrid.com", "DX Team"),
				Subject = "Hello World from the SendGrid CSharp SDK!",
				PlainTextContent = "Hello, Email!",
				HtmlContent = "<strong>Hello, Email!</strong>"
			};
			msg.AddTo(new EmailAddress("elmer.thomas@sendgrid.com", "Test User"));
			var base64ImgAttachment = "iVBOR ... RK5CYII=";
			msg.AddAttachment("Capture", base64ImgAttachment, "image/png");
			var response = await client.SendEmailAsync(msg);
		}
	}
}
```

Couple things to note:

1. I had to remove the metadata
2. The first test, I received the same error as you. Turns out I had only pasted part of the base64 string. When I verified I had copied the entire base64 encoding it worked.

**Comment by ChristopheHvd** [comment] 2017-03-16 09:09
Hi Elmer,
So, if I understand correctly what you said : you did exactly the same thing as me (removing the metadata) and it works? Like I did previously.
So, you don't have any explanation why it doesn't work in the first place?

**Comment by thinkingserious** [comment] 2017-03-16 16:34
@ChristopheHvd,

My guess is that your base64 encoded string was truncated. That was what made the error happen for me. Somehow when I first manually encoded it, I did not copy the whole string.

**Comment by thinkingserious** [comment] 2017-06-07 23:51
Hello @ChristopheHvd,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Closed by thinkingserious** 2017-06-07 23:51 UTC
Labels: status: help wanted, type: archive, type: question
